// auth
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const GET_AUTH_USER = 'GET_AUTH_USER';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const UPDATE_AUTH_USER = 'UPDATE_AUTH_USER';

// User Actions
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_SPECIFIC_USER = "GET_SPECIFIC_USER";
export const CREATE_NEW_USER = "CREATE_NEW_USER";
export const UPDATE_SPECIFIC_USER = "UPDATE_SPECIFIC_USER";
export const REMOVE_USERS = "REMOVE_USERS";

// Customer Actions
export const GET_ALL_CUSTOMERS = "GET_ALL_CUSTOMERS";
export const GET_ALL_CUSTOMERS_WITH_CONCATENATE =
    "GET_ALL_CUSTOMERS_WITH_CONCATENATE";
export const GET_SPECIFIC_CUSTOMER = "GET_SPECIFIC_CUSTOMER";
export const CREATE_NEW_CUSTOMER = "CREATE_NEW_CUSTOMER";
export const UPDATE_SPECIFIC_CUSTOMER = "UPDATE_SPECTIFIC_CUSTOMER";
export const REMOVE_CUSTOMERS = "REMOVE_CUSTOMERS";
export const UPDATE_STATUS_CUSTOMERS = "UPDATE_STATUS_CUSTOMERS";
export const CUSTOMER_REVIEWS = "CUSTOMER_REVIEWS";
export const DOWNLOAD_CUSTOMERS = "DOWNLOAD_CUSTOMERS";

//notification Actions
export const GET_ALL_NOTIFICATIONS = "GET_ALL_NOTIFICATIONS";
export const GET_SPECIFIC_NOTIFICATION = "GET_SPECIFIC_NOTIFICATION";
export const CREATE_NEW_NOTIFICATION = "CREATE_NEW_NOTIFICATION";
export const UPDATE_SPECIFIC_NOTIFICATION = "UPDATE_SPECIFIC_NOTIFICATION";
export const REMOVE_NOTIFICATIONS = "REMOVE_NOTIFICATIONS";

//request Actions
export const GET_ALL_REQUESTS = "GET_ALL_REQUEST";
export const GET_SPECIFIC_REQUEST = "GET_SPECIFIC_REQUEST";
export const UPDATE_SPECIFIC_REQUEST = "UPDATE_SPECIFIC_REQUEST";
export const RESPONSE_REQUEST = "RESPONSE_REQUEST";
export const CREATE_REQUEST = "CREATE_REQUEST";
export const DOWNLOAD_REQUEST = "DOWNLOAD_REQUEST";

//documentation Actions
export const GET_ALL_DOCUMENTATIONS = "GET_ALL_DOCUMENTATIONS";
export const GET_SPECIFIC_DOCUMENTATION = "GET_SPECIFIC_DOCUMENTATION";
export const CREATE_NEW_DOCUMENTATION = "CREATE_NEW_DOCUMENTATION";
export const UPDATE_SPECIFIC_DOCUMENTATION = "UPDATE_SPECIFIC_DOCUMENTATION";
export const REMOVE_DOCUMENTATIONS = "REMOVE_DOCUMENTATIONS";

// product
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_RENEWED_PRODUCTS = "GET_RENEWED_PRODUCTS";
export const GET_SPECIFIC_PRODUCT = "GET_SPECIFIC_PRODUCT";
export const CREATE_NEW_PRODUCT = "CREATE_NEW_PRODUCT";
export const UPDATE_SPECIFIC_PRODUCT = "UPDATE_SPECIFIC_PRODUCT";
export const REMOVE_PRODUCTS = "REMOVE_PRODUCTS";
export const CREATE_EXPLANATIONS = "CREATE_EXPLANATIONS";
export const CREATE_CONTRACT = "CREATE_CONTRACT";
export const CREATE_RENEWAL_MAIL = "CREATE_RENEWAL_MAIL";
export const UPDATE_RENEWAL_MAIL = "UPDATE_RENEWAL_MAIL";
export const REMOVE_RENEWAL_MAIL = "REMOVE_RENEWAL_MAIL";
export const DOWNLOAD_PRODUCT_DATA = "DOWNLOAD_PRODUCT_DATA";
export const SEND_POSTAGE = "SEND_POSTAGE";
export const SEND_OVERLOAD_ALERT = "SEND_OVERLOAD_ALERT";
export const GET_LATEST_PRODUCT_OF_CUSTOMER = 'GET_LATEST_PRODUCT_OF_CUSTOMER';
export const DOWNLOAD_PRODUCT_HISTORIES = 'DOWNLOAD_PRODUCT_HISTORIES';
export const REMOVE_CONTRACT = "REMOVE_CONTRACT";

//service
export const GET_ALL_SERVICES = "GET_ALL_SERVICES";
export const GET_SPECIFIC_SERVICE = "GET_SPECIFIC_SERVICE";
export const CREATE_NEW_SERVICE = "CREATE_NEW_SERVICE";
export const UPDATE_SPECIFIC_SERVICE = "UPDATE_SPECIFIC_SERVICE";
export const REMOVE_SERVICES = "REMOVE_SERVICES";

// category Actions
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const GET_SPECIFIC_CATEGORY = "GET_SPECIFIC_CATEGORY";
export const CREATE_NEW_CATEGORY = "CREATE_NEW_CATEGORY";
export const UPDATE_SPECIFIC_CATEGORY = "UPDATE_SPECIFIC_CATEGORY";
export const REMOVE_CATEGORIES = "REMOVE_CATEGORIES";

//partner Actions
export const GET_ALL_PARTNERS = "GET_ALL_PARTNERS";
export const GET_SPECIFIC_PARTNER = "GET_SPECIFIC_PARTNER";
export const CREATE_NEW_PARTNER = "CREATE_NEW_PARTNER";
export const UPDATE_SPECIFIC_PARTNER = "UPDATE_SPECIFIC_PARTNER";
export const REMOVE_PARTNERS = "REMOVE_PARTNERS";

//datacenter requests
export const GET_ALL_DATACENTER_REQUESTS = "GET_ALL_DATACENTER_REQUESTS";
export const GET_SPECIFIC_DATACENTER_REQUEST =
    "GET_SPECIFIC_DATACENTER_REQUEST";
export const CREATE_NEW_DATACENTER_REQUEST = "CREATE_NEW_DATACENTER_REQUEST";
export const UPDATE_SPECIFIC_DATACENTER_REQUEST =
    "UPDATE_SPECIFIC_DATACENTER_REQUEST";
export const REMOVE_DATACENTER_REQUESTS = "REMOVE_DATACENTER_REQUESTS";
export const DOWNLOAD_DATACENTER_REQUESTS = "DOWNLOAD_DATACENTER_REQUESTS";

// permission
export const GET_ALL_PERMISSIONS = "GET_ALL_PERMISSIONS";
export const UPDATE_ROLE_PERMISSIONS = "UPDATE_ROLE_PERMISSIONS";
export const GET_PERMISSIONS_BY_ROLE = "GET_PERMISSIONS_BY_ROLE";
export const GET_PERMISSIONS_BY_USER = "GET_PERMISSIONS_BY_USER";

// statistic
export const STATISTIC_GENERAL = "STATISTIC_GENERAL";
export const STATISTIC_PRODUCTS = "STATISTIC_PRODUCTS";
export const STATISTIC_PRODUCTS_BY_CATEGORY = "STATISTIC_PRODUCTS_BY_CATEGORY";
export const STATISTIC_SUPPORT_REQUESTS = "STATISTIC_SUPPORT_REQUESTS";
export const STATISTIC_USERS = "STATISTIC_USERS";
export const STATISTIC_REVENUE_IN_MONTH = "STATISTIC_REVENUE_IN_MONTH";
export const GET_REPORT_OF_USER = "GET_REPORT_OF_USER";
export const GET_REPORT_OF_STAFFS = "GET_REPORT_OF_STAFFS";
export const STATISTIC_CUSTOMER_IN_MONTH = "STATISTIC_CUSTOMER_IN_MONTH";
export const STATISTIC_COUNT_REQUESTS = "STATISTIC_COUNT_REQUESTS";
export const STATISTIC_CATEGORY = "STATISTIC_CATEGORY";
export const STATISTIC_PRODUCT_HISTORY = "STATISTIC_PRODUCT_HISTORY";
export const STATISTIC_PENDING = "STATISTIC_PENDING";
export const STATISTIC_COUNT_HISTORY_CHANGE = "STATISTIC_COUNT_HISTORY_CHANGE";
export const STATISTIC_BY_USER = 'STATISTIC_BY_USER';
export const STATISTIC_REVENUES = "STATISTIC_REVENUES";
export const STATISTIC_BUSINESS_REVENUES = "STATISTIC_BUSINESS_REVENUES";

// CustomerHistory
export const GET_ALL_CUSTOMER_HISTORY = "GET_ALL_CUSTOMER_HISTORY";
export const CREATE_CUSTOMER_HISTORY = "CREATE_CUSTOMER_HISTORY";
export const REMOVE_CUSTOMER_HISTORY = "REMOVE_CUSTOMER_HISTORY";
export const DOWNLOAD_CUSTOMER_HISTORY = 'DOWNLOAD_CUSTOMER_HISTORY';

// task
export const GET_ALL_TASKS = "GET_ALL_TASKS";
export const GET_SPECIFIC_TASK = "GET_SPECIFIC_TASK";
export const CREATE_NEW_TASK = "CREATE_NEW_TASK";
export const UPDATE_SPECIFIC_TASK = "UPDATE_SPECIFIC_TASK";
export const REMOVE_TASKS = "REMOVE_TASKS";

// role
export const GET_ALL_ROLES = "GET_ALL_ROLES";
export const CREATE_NEW_ROLE = "CREATE_NEW_ROLE";
export const UPDATE_SPECIFIC_ROLE = "UPDATE_SPECIFIC_ROLE";
export const REMOVE_ROLES = "REMOVE_ROLES";

// potential customer
export const GET_ALL_POTENTIAL_CUSTOMERS = "GET_ALL_POTENTIAL_CUSTOMERS";
export const CREATE_NEW_POTENTIAL_CUSTOMER = "CREATE_NEW_POTENTIAL_CUSTOMER";
export const GET_SPECIFIC_POTENTIAL_CUSTOMER =
    "GET_SPECIFIC_POTENTIAL_CUSTOMER";
export const UPDATE_SPECIFIC_POTENTIAL_CUSTOMER =
    "UPDATE_SPECIFIC_POTENTIAL_CUSTOMER";
export const REMOVE_POTENTIAL_CUSTOMERS = "REMOVE_POTENTIAL_CUSTOMERS";
export const UPLOAD_FILE = "UPLOAD_FILE";
export const CREATE_CUSTOMER_FROM_POTENTIAL_CUSTOMER =
    "CREATE_CUSTOMER_FROM_POTENTIAL_CUSTOMER";

// config
export const GET_CONFIG = "GET_CONFIG";
export const SET_CONFIG = "SET_CONFIG";

//transaction
export const GET_ALL_TRANSACTIONS = "GET_ALL_TRANSACTIONS";
export const GET_SPECIFIC_TRANSACTION = "GET_SPECIFIC_TRANSACTION";
export const CREATE_NEW_TRANSACTION = "CREATE_NEW_TRANSACTION";
export const UPDATE_SPECIFIC_TRANSACTION = "UPDATE_SPECIFIC_TRANSACTION";
export const REMOVE_TRANSACTIONS = "REMOVE_TRANSACTIONS";

//warehouses
export const GET_ALL_WAREHOUSES = "GET_ALL_WAREHOUSES";
export const GET_SPECIFIC_WAREHOUSE = "GET_SPECIFIC_WAREHOUSE";
export const CREATE_NEW_WAREHOUSE = "CREATE_NEW_WAREHOUSE";
export const UPDATE_SPECIFIC_WAREHOUSE = "UPDATE_SPECIFIC_WAREHOUSE";
export const REMOVE_WAREHOUSES = "REMOVE_WAREHOUSES";

//shop
export const GET_ALL_SHOPS = "GET_ALL_SHOPS";
export const GET_SPECIFIC_SHOP = "GET_SPECIFIC_SHOP";
export const CREATE_NEW_SHOP = "CREATE_NEW_SHOP";
export const UPDATE_SPECIFIC_SHOP = "UPDATE_SPECIFIC_SHOP";
export const REMOVE_SHOPS = "REMOVE_SHOPS";

// order
export const GET_ALL_ORDERS = 'GET_ALL_ORDERS';
export const GET_SPECIFIC_ORDER = 'GET_SPECIFIC_ORDER';
export const UPDATE_SPECIFIC_ORDER = 'UPDATE_SPECIFIC_ORDER';

// service category
export const GET_ALL_SERVICE_CATEGORIES = "GET_ALL_SERVICE_CATEGORIES";
export const CREATE_NEW_SERVICE_CATEGORY = "CREATE_NEW_SERVICE_CATEGORY";
export const UPDATE_SPECIFIC_SERVICE_CATEGORY = "UPDATE_SPECIFIC_SERVICE_CATEGORY";
export const REMOVE_SERVICE_CATEGORIES = "REMOVE_SERVICE_CATEGORIES";

// mail
export const SEND_MAIL = 'SEND_MAIL';
export const GET_MAIL_TEMPLATE = 'GET_MAIL_TEMPLATE';
export const UPDATE_MAIL_TEMPLATE = 'UPDATE_MAIL_TEMPLATE';

// web customer
export const GET_ALL_WEB_CUSTOMERS = "GET_ALL_WEB_CUSTOMERS";
export const GET_SPECIFIC_WEB_CUSTOMER = "GET_SPECIFIC_WEB_CUSTOMER";
export const UPDATE_SPECIFIC_WEB_CUSTOMER = "UPDATE_SPECIFIC_WEB_CUSTOMER";
export const REMOVE_WEB_CUSTOMERS = "REMOVE_WEB_CUSTOMERS";

// download request
export const CREATE_DOWNLOAD_REQUEST = 'CREATE_DOWNLOAD_REQUEST';
export const CONFIRM_DOWNLOAD_REQUEST = 'CONFIRM_DOWNLOAD_REQUEST';

// edit product requests
export const LIST_ALL_PENDING_UPDATE_PRODUCT_REQUESTS = 'LIST_ALL_PENDING_UPDATE_PRODUCT_REQUESTS';
export const LIST_ALLOWED_UPDATE_PRODUCT_REQUESTS = 'LIST_ALLOWED_UPDATE_PRODUCT_REQUESTS';
export const CREATE_UPDATE_PRODUCT_REQUEST = 'CREATE_UPDATE_PRODUCT_REQUEST';
export const CONFIRM_UPDATE_PRODUCT_REQUEST = 'CONFIRM_UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_BASED_ON_REQUEST = 'UPDATE_PRODUCT_BASED_ON_REQUEST';
export const UPDATE_MANY_PRODUCTS_BASED_ON_REQUEST = 'UPDATE_MANY_PRODUCTS_BASED_ON_REQUEST';

// product overload
export const LIST_ALL_PRODUCT_OVERLOAD_ALERTS = 'LIST_ALL_PRODUCT_OVERLOAD_ALERTS';
export const DOWNLOAD_PRODUCT_OVERLOAD_ALERTS = 'DOWNLOAD_PRODUCT_OVERLOAD_ALERTS';

// support calls
export const GET_ALL_PENDING_CUSTOMERS = "GET_ALL_PENDING_CUSTOMERS";
export const CREATE_SUPPORT_CALL_NOTE = "CREATE_SUPPORT_CALL_NOTE";
export const GET_OLD_NOTES_OF_SPECIFIC_CUSTOMER = "GET_OLD_NOTES_OF_SPECIFIC_CUSTOMER";

// edit customer requests
export const LIST_ALL_PENDING_UPDATE_CUSTOMER_REQUESTS = 'LIST_ALL_PENDING_UPDATE_CUSTOMER_REQUESTS';
export const LIST_ALLOWED_UPDATE_CUSTOMER_REQUESTS = 'LIST_ALLOWED_UPDATE_CUSTOMER_REQUESTS';
export const CREATE_UPDATE_CUSTOMER_REQUEST = 'CREATE_UPDATE_CUSTOMER_REQUEST';
export const CONFIRM_UPDATE_CUSTOMER_REQUEST = 'CONFIRM_UPDATE_CUSTOMER_REQUEST';
export const UPDATE_CUSTOMER_BASED_ON_REQUEST = 'UPDATE_CUSTOMER_BASED_ON_REQUEST';